### ISSUE TITLE
Crash ExFusile

### ISSUE THREAD

**Issue by Pilad** [WanionCane/ExFusile#1]
Crash https://pastebin.com/pcyffKCv

**Comment by Pilad** [comment]
But even without mod as crash, Hm..

**Comment by WanionCane** [comment]
this crash seems to be related to TConstruct, be sure that it's jar isn't corrupt.

**Comment by WanionCane** [comment]
also, be sure that your java is updated, I've seen a lot of issues with outdated java versions.
happy new year! =P

**Comment by Pilad** [comment]
COFH needs ))) https://github.com/SlimeKnights/TinkersConstruct/issues/1149
